interface Resources {
  "fa": {
    "AUTH.FORGOT.TITLE": "رمزعبور را رافموش کرده‌اید؟",
    "AUTH.GENERAL.FORGOT_BUTTON": "فراموشی رمزعبور",
    "AUTH.GENERAL.NO_ACCOUNT": "حساب کاربری ندارید؟",
    "AUTH.GENERAL.OR": "یا",
    "AUTH.GENERAL.SIGNUP_BUTTON": "ثبت‌نام",
    "AUTH.GENERAL.SUBMIT_BUTTON": "ارسال",
    "AUTH.INPUT.EMAIL": "ایمیل",
    "AUTH.INPUT.FULLNAME": "نام",
    "AUTH.INPUT.PASSWORD": "رمز عبور",
    "AUTH.INPUT.USERNAME": "نام کاربری",
    "AUTH.LOGIN.BUTTON": "ورود",
    "AUTH.LOGIN.TITLE": "پنل مدیریت مطب",
    "AUTH.VALIDATION.INVALID": "{name} معتبر نمی‌باشد",
    "AUTH.VALIDATION.REQUIRED": "{name} اجباری می‌باشد",
    "Actions.Active": "فعال",
    "Actions.ActiveDeactive": "فعال/غیرفعال",
    "Actions.Add": "افزودن",
    "Actions.AddQuestion": "افزودن سوال",
    "Actions.Approve": "تایید",
    "Actions.ApproveFinacialTransfer": "تایید درخواست پرداخت",
    "Actions.Approved": "تایید شد",
    "Actions.Back": "بازگشت",
    "Actions.Cancel": "انصراف",
    "Actions.Check": "بررسی",
    "Actions.Checking": "در حال بررسی",
    "Actions.Close": "بستن",
    "Actions.DeleteConfirm": "آیا از حذف «{{0}}» اطمینان دارید؟",
    "Actions.DeleteForm": "حذف {{0}}",
    "Actions.Deliver": "تحویل",
    "Actions.Edit": "ویرایش",
    "Actions.EvidenceReview": "بررسی مدرک",
    "Actions.ExportAllPRofileExcel": "خروجی اکسل کل مشتریان",
    "Actions.ExportExcel": "خروجی اکسل",
    "Actions.ExportFilledProfileExcel": "خروجی اکسل پروفایل های تکمیل شده",
    "Actions.ExportFilledProfileInRangeExcel": "خروجی اکسل پروفایل های تکمیل شده در بازه تاریخی",
    "Actions.IsApproveing": "در حال تایید",
    "Actions.IsRejectiong": "در حال رد",
    "Actions.IsWaitingForApprove": "در حال ارسال برای تایید",
    "Actions.MakeActive": " فعال سازی",
    "Actions.MakeDeactive": " غیر فعال سازی",
    "Actions.New": "جدید",
    "Actions.NextStep": "مرحله بعد",
    "Actions.No": "خیر",
    "Actions.Ok": "تایید",
    "Actions.Operation": "عملیات",
    "Actions.Pay": "پرداخت",
    "Actions.PleaseWait": "منتظر بمانید...",
    "Actions.Print": "چاپ",
    "Actions.Processing": "در حال بارگذاری...",
    "Actions.Reject": "رد",
    "Actions.RejectFinacialTransfer": "رد درخواست پرداخت",
    "Actions.Rejected": "رد شد",
    "Actions.Remove": "حذف",
    "Actions.Reset": "بارگذاری",
    "Actions.Save": "ذخیره",
    "Actions.Pending": "در حال انجام عملیات",
    "Actions.SavenExit": "ذخیره و خروج",
    "Actions.Search": "جستجو",
    "Actions.Select": "انتخاب کنید",
    "Actions.Show": "نمایش",
    "Actions.Submit": "ثبت",
    "Actions.Submitting": "درحال ثبت",
    "Actions.UpdateStatusConfirm": "آیا از فعال‌سازی «{{0}}» اطمینان دارید؟",
    "Actions.UpdateStatusForm": "فعال‌سازی {{0}}",
    "Actions.WaitingForApprove": "ارسال برای تایید",
    "Actions.WaitingForApproveFinacialTransfer": "ارسال برای تایید درخواست پرداخت",
    "Actions.WaittedForApprove": "در انتظار تایید شد",
    "Actions.Yes": "بله",
    "Actions.Create": "جدید",
    "Actions.Filter": "فیلتر",
    "Address.ApartmentNo": "پلاک",
    "Address.City": "شهر",
    "Address.FullAddress": "آدرس کامل",
    "Address.PostalCode": "کدپستی",
    "Address.Province": "استان",
    "Address.Title": "آدرس",
    "Address.UnitNo": "واحد",
    "AirportService": "درخواست تشریفات فرودگاهی",
    "AirportService.CardNumber": "شماره کارت",
    "AirportService.Cartable": "کارتابل",
    "AirportService.DestinationAirport": "فرودگاه مقصد",
    "AirportService.FlightDateTime": "تاریخ پرواز",
    "AirportService.FromFlightDate": "از تاریخ پرواز",
    "AirportService.OriginAirport": "فرودگاه مبدا",
    "AirportService.Providers": "تامین کننده",
    "AirportService.RequestDate": "تاریخ درخواست",
    "AirportService.RequestedServicesNo": "تعداد خدمات درخواستی",
    "AirportService.ServiceType": "نوع خدمات",
    "AirportService.Title": "تشریفات فرودگاهی",
    "AirportService.ToFlightDate": "تا تاریخ پرواز",
    "AirportService.TraceNo": "شماره پیگیری",
    "AirportService.TransferProviders": "تامین کننده سرویس ترنسفر",
    "AirportService.VipProviders": "تامین کننده سرویس VIP",
    "App.About": "درباره",
    "App.CompanyName": "اباذریان",
    "App.Contact": "تماس",
    "App.Modules": "ماژول‌ها",
    "App.Name": "پنل مدیریت مطب",
    "App.Purchase": "خرید",
    "Appointment.AppointmentDate": "تاریخ نوبت",
    "Appointment.AppointmentPurpose": "هدف نوبت",
    "Appointment.AppointmentStatus": "وضعیت نوبت",
    "Appointment.DoctorName": "نام پزشک",
    "Appointment.PatientName": "نام بیمار",
    "AppointmentRequest.AppointmentDate": "تاریخ نوبت",
    "AppointmentRequest.AppointmentRequestStatus": "وضعیت درخواست نوبت",
    "AppointmentRequest.AppointmentTime": "زمان نوبت",
    "AppointmentRequest.PatientName": "نام بیمار",
    "AppointmentRequest.PhoneNumber": "تلفن",
    "BasicInfo.AppointmentPurpose": "هدف از نوبت",
    "BasicInfo.AppointmentRequestStatus": "وضعیت درخواست نوبت",
    "BasicInfo.AppointmentStatus": "وضعیت نوبت",
    "BasicInfo.DoctorStatus": "وضعیت پزشک",
    "BasicInfo.DocumentType": "نوع سند",
    "BasicInfo.Educationlevel": "سطح تحصیلات",
    "BasicInfo.ImageUsageType": "نوع استفاده از تصویر",
    "BasicInfo.MaritalStatus": "وضعیت تاهل",
    "BasicInfo.MedicalSpecialty": "تخصص پزشکی",
    "BasicInfo.PatientStatus": "وضعیت بیمار",
    "BasicInfo.PhoneNumberType": "نوع شماره تلفن",
    "BasicInfo.Title": "عنوان",
    "BasicInfo.TreatmentType": "نوع درمان",
    "BasicInfo.VisitReason": "دلیل مراجعه",
    "Cards.Title": "کارت های من",
    "CashbackClaim": "درخواست بررسی برگشت نقدی",
    "CashbackClaim.Accept": "پذیرفتن",
    "CashbackClaim.Accepted": "پذیرفته شده",
    "CashbackClaim.Amount": "مبلغ (ریال)",
    "CashbackClaim.BranchName": "نام پذیرنده",
    "CashbackClaim.CardNo": "شماره کارت",
    "CashbackClaim.CashbackClaimActionType": "نوع عملیات",
    "CashbackClaim.CashbackClaimCheckingResult": "نتیجه بررسی",
    "CashbackClaim.CashbackClaims": "درخواست‌های برگشت نقدی",
    "CashbackClaim.Checking": "درحال بررسی",
    "CashbackClaim.CustomerFullName": "نام مشتری",
    "CashbackClaim.Date": "تاریخ درخواست",
    "CashbackClaim.Details": "جزئیات درخواست بررسی برگشت نقدی",
    "CashbackClaim.FromDate": "از تاریخ ثبت",
    "CashbackClaim.InitialSubmit": "ثبت اولیه",
    "CashbackClaim.InsertDate": "تاریخ ثبت",
    "CashbackClaim.LastCheckingDate": "تاریخ آخرین بررسی",
    "CashbackClaim.ModifiedDate": "تاریخ ویرایش",
    "CashbackClaim.NationalCode": "کدملی مشتری",
    "CashbackClaim.OperatorResponse": "پاسخ کاربر بررسی کننده",
    "CashbackClaim.OperatorResponseResult": "نتیجه بررسی",
    "CashbackClaim.PhoneNumber": "شماره تماس مشتری",
    "CashbackClaim.ReceiptFile": "فایل رسید",
    "CashbackClaim.ReferenceNo": "شماره پیگیری تراکنش",
    "CashbackClaim.Reject": "رد کردن",
    "CashbackClaim.Rejected": "رد شده",
    "CashbackClaim.Request": "ثبت درخواست",
    "CashbackClaim.ShowDetails": "مشاهده جزئیات",
    "CashbackClaim.StatisticsPerBranch": "آمار کل اعتراضات پذیرنده",
    "CashbackClaim.StatisticsPerTerminal": "آمار کل اعتراضات ترمینال",
    "CashbackClaim.StatisticsPerUser": "آمار کل اعتراضات مشتری",
    "CashbackClaim.Status": "وضعیت درخواست",
    "CashbackClaim.SystemUserFullName": "کاربر بررسی کننده",
    "CashbackClaim.TerminalNo": "شماره ترمینال",
    "CashbackClaim.ToDate": "تا تاریخ ثبت",
    "CashbackClaim.TransactionDate": "تاریخ تراکنش",
    "CashbackClaim.UserComment": "توضیحات",
    "CashbackClaimCheck": "بررسی برگشت نقدی",
    "CashbackClaims": "مدیریت درخواست برگشت نقدی",
    "Common.Active": "فعال",
    "Common.Inactive": "غیرفعال",
    "Common.New": "جدید",
    "ContantInfo.Phones": "تلفن‌ها",
    "ContantInfo.Title": "اطلاعات تماس",
    "Customer.Survey": "نظرسنجی",
    "Customer.Transaction.Report": "تراکنش‌های خرید",
    "CustomerTransaction.Transaction.Acno": "شماره حساب",
    "CustomerTransaction.Transaction.BranchName": "نام فروشگاه",
    "CustomerTransaction.Transaction.CardNumber": "شماره کارت",
    "CustomerTransaction.Transaction.Date": "تاریخ",
    "CustomerTransaction.Transaction.EmtiazErtegha": "امتیاز ارتقا",
    "CustomerTransaction.Transaction.EmtiazNaghdi": "برگشت نقدی عادی",
    "CustomerTransaction.Transaction.FromDate": "از تاریخ",
    "CustomerTransaction.Transaction.MerchantEmtiazNaghdi": "برگشت نقدی فروشگاهی",
    "CustomerTransaction.Transaction.Name_Majmoue": "نام مجموعه",
    "CustomerTransaction.Transaction.NormalCashback": "برگشت نقدی عادی",
    "CustomerTransaction.Transaction.PointType": "نوع امتیاز نقدی",
    "CustomerTransaction.Transaction.ReferenceNo": "شماره پیگیری تراکنش",
    "CustomerTransaction.Transaction.ShopCashback": "برگشت نقدی فروشگاهی",
    "CustomerTransaction.Transaction.ToDate": "تا تاریخ",
    "CustomerTransaction.Transaction.TranAmount": "مبلغ",
    "CustomerTransaction.Transaction.TranDate": "تاریخ تراکنش",
    "CustomerTransaction.Transaction.TranTime": "ساعت تراکنش",
    "CustomerTransaction.Transaction.VipCashback": "برگشت نقدی خدمات ویژه",
    "CustomerTransaction.Transaction.VipEmtiazNaghdi": "برگشت نقدی ویژه",
    "CustomerTransactions.Search": "جستجو",
    "Doctor.AddressLine": "آدرس",
    "Doctor.DateOfBirth": "تاریخ تولد",
    "Doctor.DoctorStatusName": "وضعیت",
    "Doctor.Email": "ایمیل",
    "Doctor.FirstName": "نام",
    "Doctor.LastName": "نام خانوادگی",
    "Doctor.MedicalSpecialtyName": "تخصص",
    "Doctor.PhoneNumber": "تلفن همراه",
    "Financial.Admin": "مدیریت مالی",
    "Financial.Cartable": "کارتابل مالی",
    "Financial.DownloadSampleFile": "دانلود فایل نمونه",
    "Financial.FromAccount": "حساب مبدا",
    "Financial.InvalidRowRecordsAreAvailableInExcelFile": "تعداد {{0}} رکورد خطا خورده در فایل اکسل دانلود شده قابل مشاهده می‌باشند",
    "Financial.RefundMoney": "استرداد وجه",
    "Financial.RefundMoney.AccHolder": " صاحب حساب {{0}} {{1}} می باشد",
    "Financial.RefundMoney.AccNumber": "شماره حساب",
    "Financial.RefundMoney.AccNumberMinlenght": "شماره حساب حداقل 12 رقم دارد",
    "Financial.RefundMoney.Amount": "مبلغ",
    "Financial.RefundMoney.Description": "شرح",
    "Financial.RefundMoney.FromBankAccount": "شماره حساب مبدا",
    "Financial.RefundMoney.InvalidAcc": "شماره حساب نا معتبر است ",
    "Financial.RefundMoney.Modal": "متعلق به  ",
    "Financial.RefundMoney.NotANumber": "لطفا فقط عدد وارد کنید",
    "Financial.RefundMoney.RefNumber": "شماره رهگیری",
    "Financial.RefundMoney.WithAccNo": "استرداد وجه با شماره حساب",
    "Financial.RefundMoneyWithExcel": "استرداد وجه از طریق اکسل",
    "Financial.Report": "گزارش انتقال وجه و استرداد",
    "Financial.Report.Amount": "مبلغ",
    "Financial.Report.Description": "توضیحات",
    "Financial.Report.FromAccountNo": "شماره حساب مبدا",
    "Financial.Report.FromBankAccountName": "صاحب حساب مبدا",
    "Financial.Report.InsertDateTime": "تاریخ ثبت درخواست",
    "Financial.Report.OperatorFullName": "کارشناس",
    "Financial.Report.RefNumber": "شماره رهگیری RefNo",
    "Financial.Report.ReferenceNumber": "شماره پیگیری سرویس",
    "Financial.Report.RequestFromDate": "از تاریخ درخواست",
    "Financial.Report.RequestToDate": "تا تاریخ درخواست",
    "Financial.Report.ResponseDateTime": "تاریخ پاسخ",
    "Financial.Report.ResponseFromDate": "از تاریخ پاسخ",
    "Financial.Report.ResponseToDate": "تا تاریخ پاسخ",
    "Financial.Report.Succeeded": "وضعیت",
    "Financial.Report.ToBankAccountName": "صاحب شبا مقصد",
    "Financial.Report.ToIban": "شماره شبا مقصد",
    "Financial.Reuqest": "درخواست پرداخت",
    "Financial.Status": "وضعیت",
    "Financial.ToAccount": "حساب مقصد",
    "Financial.ToAccountOrRefNumber": "حساب مقصد یا شماره رهگیری",
    "Financial.TransferMoney": "انتقال وجه مستقیم",
    "Financial.TransferMoney.Amount": "مبلغ",
    "Financial.TransferMoney.Description": "شرح",
    "Financial.TransferMoney.FromBankAccount": "شماره حساب مبدا",
    "Financial.TransferMoney.RefNumber": "شماره رهگیری",
    "Financial.TransferMoney.ToBankAccount": "شماره شبا مقصد",
    "Forms.Edit": "ویرایش {{0}} «{{1}}»",
    "Forms.New": "{{0}} جدید",
    "Forms.SelectDate": "انتخاب تاریخ",
    "Gift.Gifts": "هدایا",
    "Gifts": "مدیریت هدایا",
    "Gifts.ActivateDate": "تاریخ فعالسازی",
    "Gifts.Amount": "مبلغ (ریال)",
    "Gifts.Api": "وب سرویس",
    "Gifts.ExcelFile": "فایل اکسل",
    "Gifts.ExpireDate": "تاریخ انقضا",
    "Gifts.FromApi": "از طریق وب سرویس",
    "Gifts.FromForm": "از طریق فرم",
    "Gifts.FullName": "نام مشتری",
    "Gifts.GetGiftDate": "تاریخ دریافت",
    "Gifts.GiftProvider": "ارائه دهنده کارت هدیه",
    "Gifts.ImportExcel": "بارگذاری اکسل",
    "Gifts.InsertDateTime": "تاریخ ثبت",
    "Gifts.InvalidRowRecordsAreAvailableInExcelFile": "تعداد {{0}} رکورد خطا خورده در فایل اکسل دانلود شده قابل مشاهده می باشند",
    "Gifts.NationalCode": "کدملی",
    "Gifts.Status": "وضعیت",
    "Gifts.Title": "هدایا",
    "Gifts.Type": "نوع",
    "Gifts.Unused": "استفاده نشده",
    "Gifts.Used": "استفاده شده",
    "Gifts.Voucher": "ووچر",
    "Gifts.VoucherCode": "کد ووچر",
    "Gifts.WaitingToUse": "درانتظار استفاده",
    "InsuranceCompany.Email": "ایمیل",
    "InsuranceCompany.Name": "نام شرکت",
    "InsuranceCompany.PhoneNumber": "تلفن",
    "MENU.ACTIONS": "عملیات",
    "MENU.APPS": "اپ‌ها",
    "MENU.CREATE_POST": "ایجاد پست جدید",
    "MENU.DASHBOARD": "پیشخوان",
    "MENU.FEATURES": "ویژگی‌ها",
    "MENU.NEW": "جدید",
    "MENU.PAGES": "صفحات",
    "MedicalDocument.Title": "مدارک پزشکی",
    "Merchant.Entity": "پذیرنده",
    "Merchant.Plural": "پذیرندگان",
    "Merchant.Transaction.Amount": "مبلغ تراکنش",
    "Merchant.Transaction.CardNumber": "شماره کارت",
    "Merchant.Transaction.Chart": "نمودار تعداد تراکنش در ماه",
    "Merchant.Transaction.ComplexName": "نام مجموعه",
    "Merchant.Transaction.Date": "تاریخ تراکنش",
    "Merchant.Transaction.DiscountPercent": "درصد تخفیف شعبه",
    "Merchant.Transaction.Filter": "جستجو",
    "Merchant.Transaction.MerchantName": "نام پذیرنده",
    "Merchant.Transaction.Report": "تراکنش‌های خرید",
    "Merchant.Transaction.Table": "تراکنش‌ها",
    "Merchant.Transaction.TerminalNumber": "شماره ترمینال",
    "Merchant.Transaction.Type": "شماره ترمینال",
    "Merchant.Transaction.Wage": "کارمزد",
    "Merchant.Transactions": "تراکنش‌های پذیرنده",
    "Messages.AccordingToTheAccNumber": "با توجه به شماره حساب",
    "Messages.AccordingToTheTrackingNumber": "با توجه به شماره رهگیری",
    "Messages.ApproveQuestion": "آیا از تایید موارد انتخاب شده اطمینان دارید؟",
    "Messages.AreYouSure": "آیا اطمینان دارید؟",
    "Messages.CartableRequestSuccessful": "{{0}} با موفقیت در کارتابل ثبت شد.",
    "Messages.CartableRequestUnsuccessful": "ثبت {{0}} در کارتابل با خطا مواجه شد.",
    "Messages.Confirmation": "آیا از حذف اطمینان دارید؟",
    "Messages.Failed": "عملیات با خطا همراه شد",
    "Messages.Format": "فرمت «{{0}}» صحیح نمی‌باشد",
    "Messages.Invalid": "«{{0}}» صحیح نمی‌باشد",
    "Messages.MaxLength": "حداکثر طول «{{0}}»، «{{1}}» می‌باشد.",
    "Messages.MinLength": "حداقل طول «{{0}}»، «{{1}}» می‌باشد.",
    "Messages.NoFileSelected": "فایلی انتخاب نشده",
    "Messages.NoRecords": "هیچ رکوردی یافت نشد",
    "Messages.RejectQuestion": "آیا از رد موارد انتخاب شده اطمینان دارید؟",
    "Messages.Required": "«{{0}}» الزامی می‌باشد",
    "Messages.Success": "عملیات با موفقیت انجام شد",
    "Messages.SuccessfullImport": "تعداد {{0}} «{{1}}» با موفقیت ثبت گردید",
    "Messages.Unsuccess": "عملیات با خطا مواجه شد",
    "Messages.WaitingForApproveQuestion": "آیا از ارسال موارد انتخاب شده بری تایید اطمینان دارید؟",
    "Modules.Accounting": "حسابداری",
    "Modules.AppointmentRequest": "درخواست‌های نوبت",
    "Modules.Appointments": "نوبت‌ها",
    "Modules.BasicInfo": "اطلاعات پایه",
    "Modules.Doctors": "پزشک‌ها",
    "Modules.Groups": "گروه‌ها",
    "Modules.InsuranceCompanies": "شرکت‌های بیمه",
    "Modules.Messages": "پیام‌ها",
    "Modules.Patients": "بیماران",
    "Modules.Reporting": "گزارشگیری",
    "Modules.SMSPanel": "پنل SMS",
    "Modules.Setting": "تنظیمات",
    "Modules.Warhousing": "انبارداری",
    "Notifications": "اعلانات",
    "Patient.Address": "آدرس",
    "Patient.AddressLine": "آدرس",
    "Patient.BirthDate": "تاریخ تولد",
    "Patient.CellPhoneNo": "تلفن همراه",
    "Patient.ContactInfo": "اطلاعات تماس",
    "Patient.EducationLevelName": "تحصیلات",
    "Patient.Email": "ایمیل",
    "Patient.EmergencyPhoneNo": "تلفن اضطراری",
    "Patient.FirstName": "نام",
    "Patient.InsuranceCompanyName": "بیمه",
    "Patient.IntroductionChannel": "نحوه آشنایی",
    "Patient.LastName": "نام خانوادگی",
    "Patient.MaritalStatusName": "تاهل",
    "Patient.MedicalDocuments": "مدارک پزشکی",
    "Patient.Occupation": "شغل",
    "Patient.PatientStatusName": "وضعیت",
    "Patient.PhoneNo": "تلفن",
    "Patient.PhoneType": "نوع تلفن",
    "Patient.Title": "بیمار",
    "Profile.Address": "آدرس",
    "Profile.City": "شهر",
    "Profile.Edit": "ویرایش پروفایل",
    "Profile.PostalCode": "کدپستی",
    "Profile.Province": "استان",
    "Profile.Title": "پروفایل",
    "Question.AddOptions": "افزودن گزینه",
    "Question.AddOptionsToqs": "افزودن گزینه به سوال",
    "Question.BackToQs": "بازگشت به لیست سوالات ",
    "Question.FromInsertDateTimeQuestion": "از تاریخ ثبت سوال",
    "Question.IsActive": "فعال/غیرفعال",
    "Question.IsPositive": "مثبت/منفی",
    "Question.Option.Text": "گزینه",
    "Question.Order": "ترتیب",
    "Question.ServiceType": "نوع سرویس",
    "Question.SurveyQuestionId": "شماره سوال ",
    "Question.Text": "سوال",
    "Question.TextOption": "متن گزینه",
    "Question.ToInsertDateTimeQuestion": "تا تاریخ ثبت سوال",
    "Questions": "سوالات",
    "Questions.AddQuestions": "افزودن سوالات",
    "Questions.AddQuestionsOption": "افزودن گزینه ",
    "Questions.Delete": "حذف سوال",
    "Questions.Delete.Confirmation": "آیا از حذف سوال اطمینان دارید؟",
    "Questions.IsToggleActive.OptionText": " آیا از  {{0}} اطمینان دارید؟",
    "Questions.IsToggleActive.Text": " آیا از  {{0}}  سوال اطمینان دارید؟",
    "Questions.QuestionsOptionlist": "لیست گزینه ها",
    "Questions.Questionslist": "لیست سوالات",
    "Questions.SuccessfullyDeleted": "سوال با موفقیت حذف شد",
    "Questions.SurveyQuestionResponseType": "نوع سوال",
    "Reports": "گزارشات",
    "Reports.Cashbacks.Cardno": "شماره کارت",
    "Reports.Cashbacks.Cards": "کارت‌ها",
    "Reports.Cashbacks.Complex_Name": "نام مجموعه",
    "Reports.Cashbacks.Date": "تاریخ",
    "Reports.Cashbacks.Max_Amount": "سقف برگشت نقدی",
    "Reports.Cashbacks.Payed": "برگشت نقدی پرداخت شده",
    "Reports.Cashbacks.Unpayed": "برگشت نقدی درانتظار پرداخت",
    "Reports.CustomerExport": "گزارش پروفایل مشتریان",
    "Reports.CustomerProfile": "گزارش پروفایل مشتریان",
    "Reports.DisabledSms": "گزارش کارت ها با پیامک روزانه غیرفعال",
    "Reports.DisabledSms.AccountNumber": "شماره حساب",
    "Reports.DisabledSms.BirthDate": "تاریخ تولد",
    "Reports.DisabledSms.CardNo": "شماره کارت",
    "Reports.DisabledSms.CustomerNumber": "شماره مشتری",
    "Reports.DisabledSms.FirstName": "نام",
    "Reports.DisabledSms.HisDate": "تاریخ غیر فعال کردن",
    "Reports.DisabledSms.LastName": "نام خانوادگی",
    "Reports.DisabledSms.MobileNumber": "شماره موبایل",
    "Reports.DisabledSms.NationalCode": "کدملی",
    "Reports.ExcelMessages.FullName": "نام کاربری",
    "Reports.ExcelMessages.IsSeen": "وضعیت",
    "Reports.ExcelMessages.Messages": "ارسال پیام از طریق اکسل",
    "Reports.ExcelMessages.NationalCode": "کد ملی",
    "Reports.ExcelMessages.Subject": "موضوع",
    "Reports.ExcelMessages.UsersList": "کاربران",
    "Reports.Gift.Download": "دانلود گزارش هدایا ",
    "Reports.Gift.DownloadSampleFile": "دانلود فایل نمونه",
    "Reports.Gift.Management": "مدیریت هدایا",
    "Reports.Gift.Upload": "بارگذاری ",
    "Reports.Messages": "پیام‌ها",
    "Reports.Messages.CardColor": "نوع کارت",
    "Reports.Messages.Cardno": "شماره کارت",
    "Reports.Messages.Cards": "کارت‌ها",
    "Reports.Messages.Date": "تاریخ",
    "Reports.Messages.Subject": "موضوع",
    "Reports.Points": "امتیازها",
    "Reports.Points.Bal_amount": "امتیاز نقدی",
    "Reports.Points.Bal_point": "امتیاز موجودی",
    "Reports.Points.Cardno": "شماره کارت",
    "Reports.Points.Cards": "کارت‌ها",
    "Reports.Points.Cashback": "مبلغ کش‌بک",
    "Reports.Points.Daily_Bal_point": "امتیاز موجودی (روزانه)",
    "Reports.Points.Daily_Upgrade_point": "امتیاز ارتقا (روزانه)",
    "Reports.Points.Date": "تاریخ",
    "Reports.Points.DateRange": "بازه تاریخ",
    "Reports.Points.Total_Bal_point": "امتیاز موجودی (تجمیعی)",
    "Reports.Points.Total_CashBack": "امتیاز نقدی (تجمیعی)",
    "Reports.Points.Total_Upgrade_point": "امتیاز ارتقا (تجمیعی)",
    "Reports.Points.Upgrade_point": "امتیاز ارتقا",
    "Reports.Points.Weekly_CashBack": "امتیاز نقدی (روزانه)",
    "Reports.Reserve.Amount": "موجودی",
    "Reports.Reserve.Day": "روز",
    "Reports.Search": "جستجو",
    "Reports.Transactions": "تراکنش‌های خرید",
    "Survey": "مدیریت نظرسنجی",
    "Survey.ActivationDateTime": " تاریخ فعالسازی",
    "Survey.Add": "افزودن نظرسنجی",
    "Survey.AdminComment": "نظر مدیر",
    "Survey.Comment": "نظر کاربر",
    "Survey.Delete": "حذف نظرسنجی",
    "Survey.Delete.Confirmation": "آیا از حذف نظر سنجی اطمینان دارید؟",
    "Survey.Description": "توضیحات",
    "Survey.ExpirationDateTime": "تاریخ انقضا",
    "Survey.FromActivationDateTime": "از تاریخ فعالسازی",
    "Survey.FromCreateDate": "از تاریخ",
    "Survey.FromExpirationDateTime": "از تاریخ انقضا",
    "Survey.FromInsertDateTime": "از تاریخ ثبت",
    "Survey.FromInsertDateTimeOption": "از تاریخ ثبت گزینه",
    "Survey.InsertDateTime": "تاریخ ثبت",
    "Survey.IsActive": "وضعیت",
    "Survey.IsApproved": "وضعیت",
    "Survey.IsResponseEditable": "قابلیت ویرایش",
    "Survey.IsSatisfactionRate": "ستاره نظر سنجی",
    "Survey.IsToggleActive.Text": " آیا از  {{0}} نظر سنجی اطمینان دارید؟",
    "Survey.MerchantName": "پذیرنده",
    "Survey.OperatorResponse": "جواب ادمین",
    "Survey.SatisfactionRateNumber": "تعداد ستاره ها",
    "Survey.ServiceSatisfaction": "امتیاز",
    "Survey.ServiceType": "نوع",
    "Survey.SuccessfullyDeleted": "نظرسنجی با موفقیت حذف شد",
    "Survey.SurveyQuestionResponseType": "نوع جواب",
    "Survey.SurveyTypeId": "نوع نظرسنجی",
    "Survey.Surveys": "نظرات",
    "Survey.Title": "عنوان نظرسنجی",
    "Survey.ToActivationDateTime": "تا تاریخ فعالسازی",
    "Survey.ToCreateDate": "تا تاریخ",
    "Survey.ToExpirationDateTime": "تا تاریخ انقضا",
    "Survey.ToInsertDateTime": "تا تاریخ ثبت",
    "Survey.ToInsertDateTimeOption": "تا تاریخ ثبت گزینه",
    "Survey.UserFullName": "نام کاربر",
    "TRANSLATOR.SELECT": "زبان را انتخاب کنید",
    "Text.BeDeposited": "واریز گردد",
    "Text.BelongsTo": "متعلق به",
    "Text.Equal": "معادل",
    "Text.RejectReason": "دلیل رد درخواست",
    "Text.Rials": "ریال",
    "Text.Successful": "موفق",
    "Text.Toman": "تومان",
    "Text.Unsuccessful": "نا موفق",
    "Vip.Address": "آدرس مبدا",
    "Vip.Airline": "نوع ایرلاین",
    "Vip.Airport": "فرودگاه",
    "Vip.AirportVipServiceType": "نوع تشریفات فرودگاهی",
    "Vip.ApproveAndSubmit": "تایید و ثبت",
    "Vip.Arrival": "ورودی",
    "Vip.ArrivalDateTime": "زمان فرود",
    "Vip.BirthDate": "تاریخ تولد",
    "Vip.CIP": "سی‌آی‌پی داخلی",
    "Vip.CardNumber": "شماره کارت",
    "Vip.Cinema": "سینما",
    "Vip.CinemaParticipantNumber": "ظرفیت",
    "Vip.CinemaReserveSubmitted": "رزرو سینما با موفقیت ثبت شد.",
    "Vip.CipReserveSubmitted": "رزرو {{0}} با موفقیت ثبت شد.",
    "Vip.City": "شهر",
    "Vip.Date": "تاریخ",
    "Vip.Departure": "خروجی",
    "Vip.Description": "توضیحات",
    "Vip.Destination": "آدرس مقصد",
    "Vip.DestinationAirport": "فرودگاه مقصد",
    "Vip.DriverPresenceDateTime": "زمان درخواستی حضور راننده",
    "Vip.DriverPresenceSuggestedDateTime": "زمان پیشنهادی حضور راننده",
    "Vip.EditRequest": "ویرایش درخواست",
    "Vip.EnFirstName": "نام لاتین",
    "Vip.EnLastName": "نام خانوادگی لاتین",
    "Vip.FastTrack": "فست ترک",
    "Vip.FirstName": "نام",
    "Vip.FlightDateTime": "تاریخ پرواز",
    "Vip.FlightInfo": "اطلاعات پرواز",
    "Vip.FlightNo": "شماره پرواز",
    "Vip.FlightNumber": "شماره پرواز",
    "Vip.FlightTime": "ساعت پرواز",
    "Vip.FlightType": "نوع پرواز",
    "Vip.ForeignCIP": "سی‌آی‌پی خارجی",
    "Vip.FullName": "نام و نام خانوادگی",
    "Vip.GenderType": "جنسیت",
    "Vip.In22Areas": "در محدوده مناطق 22 گانه",
    "Vip.IsApproved": "وضعیت بررسی",
    "Vip.IsSuburb": "حومه شهر",
    "Vip.LastName": "نام خانوادگی",
    "Vip.MainPassenger": "مسافر اصلی",
    "Vip.MovieName": "نام فیلم",
    "Vip.Name": "نام",
    "Vip.NationalCardImageAddress": "تصویر کارت ملی",
    "Vip.NationalCode": "شماره ملی",
    "Vip.Nationality": "ملیت",
    "Vip.OriginAirport": "فرودگاه مبدا",
    "Vip.Out22Areas": "خارج محدوده مناطق 22 گانه",
    "Vip.ParticipantNumber": "تعداد نفرات",
    "Vip.ParticipantsInfo": "مشخصات همراهان",
    "Vip.PassengerCount": "تعداد مسافران",
    "Vip.PassportCode": "شماره پاسپورت",
    "Vip.PassportExpireDate": "تاریخ انقضا پاسپورت",
    "Vip.PassportImageAddress": "تصویر پاسپورت",
    "Vip.PassportNo": "شماره پاسپورت",
    "Vip.PhoneNo": "شماره تماس",
    "Vip.PhoneNumber": "شماره تماس در دسترس",
    "Vip.PickupDateTime": "ساعت حضور راننده",
    "Vip.ReceivingInfo": "در حال دریافت اطلاعات",
    "Vip.ReserveCinema": "رزرو سالن اختصاصی سینما",
    "Vip.ReserveTransfer": "رزرو ترنسفر فرودگاهی",
    "Vip.Status.CorrectedByCardHolder": "تصحیح شده توسط دارنده کارت",
    "Vip.Status.ExpiredPayment": "پرداخت منقضی شده",
    "Vip.Status.InitialRequest": "ثبت اولیه",
    "Vip.Status.NeedsToBeCorrected": "نیاز به تصحیح اطلاعات",
    "Vip.Status.Processing": "درحال بررسی",
    "Vip.Status.ReadyToUse": "آماده استفاده",
    "Vip.Status.Rejected": "رد شده",
    "Vip.Status.WaitingForPayment": "درانتظار پرداخت",
    "Vip.Status.WaitingForReservation": "درانتظار رزرو",
    "Vip.SubmitCardholderInfo": "ثبت اطلاعات دارنده کارت",
    "Vip.SubmitRequest": "ثبت درخواست",
    "Vip.TicketFile": "بلیت",
    "Vip.TicketImageAddress": "تصویر بلیط",
    "Vip.TicketNo": "شماره بلیط",
    "Vip.Time": "سانس",
    "Vip.TransferReserveSubmitted": "رزرو ترنسفر فرودگاهی با موفقیت ثبت شد.",
    "Vip.TravelType": "نوع سفر",
    "Vip.UploadDocuments": "آپلود مدارک",
    "Vip.VehicleType": "نوع خودرو",
    "Vip.ViewRequests": "مشاهده درخواست‌ها",
    "Vip.VoucherFileAddress": "فایل ووچر",
    "Vip.WaitForIranCardExpertMessage": "منتظر پیام تایید و پرداخت از طرف کارشناسان ما باشید."
  }
}

export default Resources;
